apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-frontend
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp-frontend
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: myapp-db
        - name: MYSQL_USER
          value: db_user
        - name: MYSQL_PASSWORD
          value: db_pass
        - name: MYSQL_SVC
          value: myapp-db-svc
        image: puppetseteam/pfc-myapp:latest
        name: myapp-frontend
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
